theme: jekyll-theme-cayman
title: GIS, Remote Sensing, and Programming
description: I am a water resource engineer with experince in using GIS and remote sensing tools to solve natural resource problems. This page lists some of my projects.
