theme: jekyll-theme-minimal
title: GIS, Remote Sensing, and Programming
description: I am a water resource engineer with experince in using GIS and remote sensing tools to solve natural resource problems. This page lists some of my projects. <br><br> I have a PG Diploma in Geoinformatics from CDAC, Noida and an M Tech in Water Resource Management from Karunya University, Coimbatore.<br><br>This repository contains some of my work related to GIS and remote sensing.
